# Generated by Django 3.1.7 on 2021-04-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='End')),
                ('name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.RESTRICT, to='Sports.location')),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.RESTRICT, to='Sports.sports'),
        ),
    ]
