# Generated by Django 3.1.7 on 2021-04-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0002_auto_20210419_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Sports.location'),
        ),
    ]
