# Generated by Django 3.1.7 on 2021-04-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0004_auto_20210419_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='Location',
        ),
    ]
