# Generated by Django 3.1.7 on 2021-04-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0006_auto_20210419_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sports',
            options={'ordering': ['startDate', 'price']},
        ),
    ]
